apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-github
spec:
  displayName: GitHub
  author:
    name: monster
  description: 仿 GitHub 个人主页风格的 Halo 2 主题
  repo: https://github.com/dengchuanfu/halo-theme-github
  issues: https://github.com/dengchuanfu/halo-theme-github/issues
  settingName: "halo-theme-github-setting"
  configMapName: "halo-theme-github-configMap"
  customTemplates:
    page:
      - name: 留言板
        description: 带评论飘屏效果的留言板页面
        file: message.html
  version: 1.1.2
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
